config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :documents do
    resources :sections do
      member do
        patch "teacher_update", to: "sections#teacher_update"
      end
    end
  end
  resources :lessons
  resources :student_lessons
  resources :users
    resources :orders, only: [:show, :create] do
    resources :payments, only: [:new, :create]
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :documents
  has_many :sections
  has_many :student_lessons
  has_many :attended_lessons, through: :student_lessons, source: :lesson
  has_many :taught_lessons, class_name: 'Lesson', foreign_key: 'user_id'
  has_many :orders

  def name
    "#{first_name} #{last_name}"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    @user = current_user
    @document = Document.new
    @documents = @user.documents
    @orders = Order.find_by(params[:user_id])

  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.new(user_params)
    if @user.save
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

    def destroy
    @user = User.find(params[:id])
    @user.destroy
  end

    private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :user_type, :institution, :email, :encrypted_password)
  end

end

app/views/users/_assignments.html.erb
<% docs = lesson.documents.order(created_at: :desc) %>
<% docs.each do |t| %>
  <div class="assignment">
    <div class="doc-name">
      <% if t.sections.find_by(student: current_user).status == "To Do" %>
        <%= link_to edit_document_section_path(t, t.sections.where(student: current_user).first), id: "preview_#{t.id}", class: "preview_link" do %>
          <%= t.title %>
          <p>Added: <%= t.created_at.strftime("%d %b %y") %></p>
          <%= cl_image_tag t.pdf.file.public_id, format: :jpg, density: 300, class: 'files-image' %>
        <% end %>
      <% elsif t.sections.find_by(student: current_user).status == "Submitted" %>
        <div class="preview_link">
          <%= t.title %>
          <p>Added: <%= t.created_at.strftime("%d %b %y") %></p>
          <p>Awaiting live<strong>translate</strong> session</p>
        </div>
      <% elsif t.sections.find_by(student: current_user).status == "livetranslated" %>
        <%= link_to document_section_path(t, t.sections.where(student: current_user).first), id: "preview_#{t.id}", class: "preview_link" do %>
          <%= t.title %>
          <p>Added: <%= t.created_at.strftime("%d %b %y") %></p>
          <%= cl_image_tag t.pdf.file.public_id, format: :jpg, density: 300, class: 'files-image' %>
        <% end %>
      <% end %>
    </div>
    <div class="status">
      <% if t.sections.find_by(student: current_user).status == "Submitted" %>
        <div class="submitted">
          <p>Submitted</p>
        </div>
      <% elsif t.sections.find_by(student: current_user).status == "To Do"%>
          <%= link_to 'To do', document_path(t), class: "btn-to-do" %>
      <% else %>
        <div class="livetranslated">
          <a href=<%= document_section_path(t, t.sections.where(student: current_user).first) %>>live<strong>translated</strong></a>
        </div>
      <% end %>
    </div>
  </div>
<% end %>

app/views/users/_business_profile.html.erb
<div class="flex-container">
  <div class="side-bar">
    <div class="profile">
      <div class="avatar">
        <img src="https://logo.clearbit.com/<%= @user.institution %>.com?size=450">
      </div>
      <div class="name">
        <%= @user.name %> <br>
      </div>
      <div class="institution">
        <%= @user.institution %>
      </div>
    </div>
    <div class="bars">
      <ul style= "" class="nav" role="tablist">
        <li role="presentation"><a type="button" class="btn btn-biz" data-toggle="modal" data-target="#myModal">Upload</button></a></li>
        <li role="presentation" class="active"><a href="#uploaded" aria-controls="uploaded" role="tab" data-toggle="tab">View all</a></li>
        <li role="presentation"><a href="#pending" aria-controls="pending" role="tab" data-toggle="tab">Work in progress</a></li>
        <li role="presentation"><a href="#translated" aria-controls="translated" role="tab" data-toggle="tab">Translated</a></li>
         <li role="presentation"><a href="#invoices" aria-controls="invoices" role="tab" data-toggle="tab">Invoices</a></li>
      </ul>
    </div>
  </div>

  <!-- Tab panes -->
  <div class="page">
  <div class="tab-content">
<div role="tabpanel" class="tab-pane active" id="uploaded">
              <div class="lesson-name">
             Uploaded Documents
           </div>
          <div class="doc-count">
                   <% i = 0 %>
            <% @documents.each do |document| %>
            <% if document.pdf? %>
              <% i += 1 %>
              <% end %>
            <% end %>
          <p><%= i %> documents</p>
              </div>
              <% docs = @documents.order(created_at: :desc) %>
              <% docs.each do |document| %>
                <div class="assignment">
                  <div class="doc-name">
                    <%= link_to document_path(document), id: "preview_#{document.id}", class: "preview_link" do %>
                      <%= document.title %>
                      <p>Added: <%= document.created_at.strftime("%d %b %y") %></p>
                      <%= cl_image_tag document.pdf.file.public_id, format: :jpg, density: 300, class: 'files-image' %>
                    <% end %>
                  </div>
                  <% if document.student_content == "paid" %>
                  <div class="btn btn-good">live<strong>translating</strong></div>
                  <% elsif document.student_content == "translated" %>
                  <%= link_to 'Download', document_path(document), :class => "btn btn-upload" %>
                  <% else %>
                  <a type="button" class="btn btn-primary" data-toggle="modal" data-target="#payment-<%= document.id %>">Purchase</button></a>
                  <a class="fas fa-times" <%= link_to '', document_path(document), method: :delete %></a>
                  <div class="modal fade" id="payment-<%= document.id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                    <div class="modal-dialog" role="document">
                      <div class="modal-content">
                        <div class="modal-header">
                          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                          <h4 class="modal-title" id="myModalLabel">Payment</h4>
                        </div>
                        <div class="modal-body">
                         <%= render 'payments/paymentform', order: document.order, document: document %>
                        </div>
                      </div>
                    </div>
                  </div>
                  <% end %>
                </div>
              <% end %>
      </div>

    <div role="tabpanel" class="tab-pane" id="pending">
          <div class="lesson-name">
         Pending Documents
       </div>
          <div class="doc-count">
            <% i = 0 %>
            <% @documents.each do |document| %>
            <% if document.student_content == "paid" %>
              <% i += 1 %>
              <% end %>
            <% end %>
          <p><%= i %> documents</p>
        </div>
        <% docs = @documents.order(created_at: :desc) %>
        <% docs.each do |t|  %>
        <% if t.student_content == "paid" %>
     <div class="assignment">
      <div class="doc-name">
        <%= link_to document_path(t), id: "preview_#{t.id}", class: "preview_link" do %>
        <%= t.title %>
        <p>Added: <%= t.updated_at.strftime("%d %b %y")%></p>
        <%# raise %>
        <%= cl_image_tag t.pdf.file.public_id, format: :jpg, density: 300, class: 'files-image' %>
        <% end %>
     </div>
        <a type="button" class="btn btn-success">live<strong>translating</strong></a>
      </div>
        <% end %>
      <% end %>
      </div>

    <div role="tabpanel" class="tab-pane" id="translated">
          <div class="lesson-name">
         Translated Documents
       </div>
          <div class="doc-count">
            <% i = 0 %>
            <% @documents.each do |document| %>
            <% if document.final_content? %>
              <% i += 1 %>
              <% end %>
            <% end %>
          <p><%= i %> documents</p>
        </div>
      <% docs = @documents.order(created_at: :desc) %>
      <% docs.each do |t|  %>
        <% if t.student_content == "translated" %>
     <div class="assignment">
      <div class="doc-name">
        <%= link_to document_path(t), id: "preview_#{t.id}", class: "preview_link" do %>
        <%= t.title %>
        <p>Added: <%= t.updated_at.strftime("%d %b %y") %></p>
        <%= cl_image_tag t.pdf.file.public_id, format: :jpg, density: 300, class: 'files-image' %>
        <% end %>
     </div>
     <!-- <a type="button" class="btn btn-upload">Download</button></a> -->
     <%= link_to 'Download', document_path(t, :format => :pdf), :class => "btn btn-upload" %>

      </div>
        <% end %>
      <% end %>
      </div>

  <div role="tabpanel" class="tab-pane" id="invoices">
          <div class="lesson-name">
         Invoices
       </div>
          <div class="doc-count">
            <% i = 0 %>
            <% @documents.each do |document| %>
            <% if !document.student_content.blank? %>
              <% i += 1 %>
              <% end %>
            <% end %>
          <p><%= i %> documents</p>
        </div>
        <% orders = @user.orders.order(created_at: :desc) %>
        <% orders.each do |t|  %>
        <% if t.state == "paid" %>
     <div class="assignment">
      <div class="doc-name invoices101">
    <%= t.document.title %> <br>
    <p>Added: <%= t.updated_at.strftime("%d %b %y") %></p>

     </div>
     £<%= t.amount_cents / 100 %> <br>
     <%= t.state.capitalize! %>
      </div>
        <% end %>
      <% end %>
      </div>



  </div>
  <!-- Modal for upload -->
  <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Upload a document</h4>
      </div>
      <div class="modal-body">
           <%= render 'documents/form', document: @document %>
      </div>
    </div>
  </div>
</div>
</div>

app/views/users/_documents.html.erb
<% @documents.each do |t| %>
 <div class="assignment">
       <div class="doc-name">
         <%= link_to edit_document_section_path(t, t), id: "preview_#{t.id}", class: "preview_link" do %>
        <%= t.title %>
        <%= cl_image_tag t.pdf.file.public_id, format: :jpg, density: 300, class: 'files-image' %>
        <% end %>
       </div>
    <div class="status">
      <% if t.original_content == "True" %>
      <div class="complete">
        <%= t.original_content %>
      </div>
      <% else %>
      <div class="to-do">
      </div>
      <% end %>
    </div>
 </div>
<% end %>

app/views/users/_lessons.html.erb
<% docs = lesson.documents.order(created_at: :desc) %>
<% docs.each do |t| %>
 <div class="assignment">
<% if t.final_content? %>
       <div class="doc-name">
      <%= link_to document_path(t), id: "preview_#{t.id}", class: "preview_link" do %>
        <%= t.title %>
        <p>Added: <%= t.created_at.strftime("%d %b %y") %></p>
        <%= cl_image_tag t.pdf.file.public_id, format: :jpg, density: 300, class: 'files-image' %>
       </div>
       <% end %>
<% else %>
       <div class="doc-name">
      <%= link_to edit_document_path(t), id: "preview_#{t.id}", class: "preview_link" do %>
        <%= t.title %>
        <p>Added: <%= t.created_at.strftime("%d %b %y") %></p>
        <%= cl_image_tag t.pdf.file.public_id, format: :jpg, density: 300, class: 'files-image' %>
       </div>
      <% end %>
      <% end %>


    <div class="status">
      <% if t.final_content? %>
  <a type="button" class="livetranslated" href=<%= document_path(t) %> >live<strong>translated</strong></a>
      <% else %>
        <a type="button" class="btn btn-upload to-do" href=<%= edit_document_path(t) %> >live<strong>translate</strong></a>
      <% end %>
    </div>
 </div>
    <% end %>

app/views/users/_student_profile.html.erb
<div class="flex-container">
  <div class="side-bar">
    <div class="profile">
      <div class="avatar">
        <%= cl_image_tag "Georges" %> <br>
      </div>
      <div class="name">
        <%= @user.name %> <br>
      </div>
      <div class="institution profession">
      <p>Student</p>
    </div>
      <div class="institution">
        <%= @user.institution %>
      </div>
    </div>
    <div class="bars">
      <ul style= "" class="nav" role="tablist">
      <% @user.attended_lessons.reverse.each_with_index do |lesson, index| %>
        <li role="presentation" class="<%= 'active' if index == 0 %>"><a href="#<%= lesson.slug %>" aria-controls="<%= lesson.slug %>" role= "tab" data-toggle="tab"><%= lesson.name %></a></li>
      <% end %>
    </ul>

    </div>
  </div>

  <div class="page">
    <div class="tab-content">
    <% if @user.attended_lessons.empty? %>
      <h1>mate no lessons</h1>
    <% end %>
    <% @user.attended_lessons.reverse.each_with_index do |lesson, index| %>
      <div role="tabpanel" class="tab-pane <%= 'active' if index == 0 %>" id="<%= lesson.slug %>">
       <div class="lesson-name">
         <%= lesson.name %>
       </div>
        <div class="doc-count">
         <p><%= lesson.documents.count %> assignments</p>
        </div>
       <%= render 'assignments', lesson: lesson %>
     </div>
    <% end %>
  </div>
  </div>
</div>

app/views/users/_teacher_profile.html.erb
<div class="flex-container">
  <div class="side-bar">
    <div class="profile">
      <div class="avatar">
        <%= cl_image_tag "Weeeeeeees" %> <br>
      </div>
      <div class="name">
        <%= @user.name %> <br>
      </div>
      <div class="institution profession">
        <p>Professor</p>
      </div>
      <div class="institution">
        <%= @user.institution %>
      </div>
    </div>
    <div class="bars">
      <ul style= "" class="nav" role="tablist">
      <% @user.taught_lessons.reverse.each_with_index do |lesson, index| %>
        <li role="presentation" class="<%= 'active' if index == 0 %>"><a href="#<%= lesson.slug %>" aria-controls="<%= lesson.slug %>" role= "tab" data-toggle="tab"><%= lesson.name %></a></li>
      <% end %>
    </ul>

    </div>
  </div>

  <div class="page">
    <div class="tab-content">
    <% if @user.taught_lessons.empty? %>
      <h1>mate no lessons</h1>
    <% end %>
    <% @user.taught_lessons.reverse.each_with_index do |lesson, index| %>
      <div role="tabpanel" class="tab-pane <%= 'active' if index == 0 %>" id="<%= lesson.slug %>">
       <div class="lesson-name">
         <%= lesson.name %>
       </div>
        <div class="doc-count">
         <p><%= lesson.documents.count %> assignments</p>
        </div>
       <%= render 'lessons', lesson: lesson %>
     </div>
    <% end %>
  </div>
  </div>
</div>

app/views/users/index.html.erb
@import "teacher_profile";
@import "student_profile";
@import "business_profile";

app/views/users/show.html.erb
<%= render 'student_profile' if current_user.user_type == 'Student'  %>
<%= render 'teacher_profile' if current_user.user_type == 'Teacher' %>
<%= render 'business_profile' if current_user.user_type == 'Business' %>