config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :documents do
    resources :sections do
      member do
        patch "teacher_update", to: "sections#teacher_update"
      end
    end
  end
  resources :lessons
  resources :student_lessons
  resources :users
    resources :orders, only: [:show, :create] do
    resources :payments, only: [:new, :create]
  end
end

app/models/section.rb
class Section < ApplicationRecord
  belongs_to :document
  belongs_to :student, class_name: 'User', foreign_key: 'user_id'

end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController

  before_action :set_document, only: [:index, :new, :update, :create, :edit, :show, :destroy]
  before_action :set_section, only: [:edit, :update, :show, :destroy]

  def index
    @sections = @document.sections
  end

  def show
    unordered = @document.sections
    @sections = unordered.order(:id)
  end

  def new
    @section = Section.new
    @students = @document.lesson.students
  end

  def create

  end
    # @section.original_content = @document
    # @section.student = @students.find(params[:section][:user_id])

  def edit
    @sections = @document.sections.order(:order)
    @students = @document.lesson.students

  end

  def update

    if @section.update(section_params)
      @section.status = "Submitted" if @section.final_content?
      @section.save
      redirect_to user_path(current_user)
    else
      render :edit
    end
  end

  def teacher_update
    @section = Section.find(params[:id])
    @section.final_content = params[:final_content]
    @section.checked = true
    @section.save!
    redirect_to edit_document_path(@section.document)
  end

  def destroy
    @section.destroy
    redirect_to document_sections_path(@document)
  end



  private

  def section_params
    params.require(:section).permit(:document_id, :final_content, :status)
  end

  def set_section
    @section = Section.find(params[:id])
  end

  def set_document
    @document = Document.find(params[:document_id])
  end

end

app/views/sections/_form.html.erb
<%= form_tag(teacher_update_document_section_path(@document, @section), method: 'patch') do |f| %>
<%#= f.association :student, collection: @students, placeholder: "Student Name" %>
<%= text_area_tag :final_content, section.original_content, id: "section-#{section.id}-content" %>
<%#= f.input :lesson, collection: @lessons.map { |lesson| lesson.lesson_name } %>
<%= button_tag type: 'submit', class: "tick", id: "register-button" do %>
        <i class="fa fa-check" aria-hidden="true"></i>
    <% end %>
<% end %>

app/views/sections/edit.html.erb
<h3 id="ed-title"><%= @document.title %></h3>
<div class="ed">
  <div class="doc">
    <div class="edit-header">
      <h4>ORIGINAL DOCUMENT</h4>
    </div>

  <div class="document-scroll">
    <div class="e-container">
      <% @sections.each do |section| %>
        <div class="<%= @section.original_content == section.original_content ? 'selected-card' : 'section-card' %>">
          <% if section.original_content.present? %>
          <p><%= section.original_content.gsub(/(\[\"|\"\])/, '').split('", "').join(" ") %></p>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

<div class="edit-container">
  <div class="edit-header">
     <h4>YOUR TRANSLATION</h4>
  </div>
  <%= simple_form_for([@document, @section], html: {id: 'fancy-btn'}) do |f| %>
    <%= f.input :final_content, :input_html => {:rows =>5}, label: false %>
  <% end %>
</div>
</div>

  <div class="button-container">
    <div class="submit-button">
      <a>
        <span>Submit</span>
        <svg class="load" version="1.1"x="0px" y="0px" width="30px" height="30px" viewBox="0 0 40 40" enable-background="new 0 0 40 40">
          <path opacity="0.3" fill="#fff" d="M20.201,5.169c-8.254,0-14.946,6.692-14.946,14.946c0,8.255,6.692,14.946,14.946,14.946
              s14.946-6.691,14.946-14.946C35.146,11.861,28.455,5.169,20.201,5.169z M20.201,31.749c-6.425,0-11.634-5.208-11.634-11.634
              c0-6.425,5.209-11.634,11.634-11.634c6.425,0,11.633,5.209,11.633,11.634C31.834,26.541,26.626,31.749,20.201,31.749z"/>
            <path fill="#fff" d="M26.013,10.047l1.654-2.866c-2.198-1.272-4.743-2.012-7.466-2.012h0v3.312h0
              C22.32,8.481,24.301,9.057,26.013,10.047z">
              <animateTransform attributeType="xml"
              attributeName="transform"
              type="rotate"
              from="0 20 20"
              to="360 20 20"
              dur="0.5s"
              repeatCount="indefinite"/>
            </path>
        </svg>
        <svg class="check" xmlns="http://www.w3.org/2000/svg" width="30" height="30" viewBox="0 0 24 24">
          <path d="M9 16.17L4.83 12l-1.42 1.41L9 19 21 7l-1.41-1.41z"/>
        </svg>
      </a>
      <div>
          <span></span>
      </div>
    </div>
  </div>
</div>

app/views/sections/index.html.erb
<div class="edit-container">
  <% @sections.each do |section| %>
    <div class="selected-card">
      <p><%= section.final_content %></p>
    </div>
  <% end %>
</div>

app/views/sections/new.html.erb
<%= render 'form', document: @document, section: @section %>

app/views/sections/show.html.erb
<!-- <div class="main-view">
  <%#= cl_image_tag @document.pdf.file.public_id, format: :jpg, density: 300, width: 800, :id => "trim", :class => "original-main" %>


</div>
<div class="previews">
  <div>
    <p>ORIGINAL PDF</p>
    <%#= cl_image_tag @document.pdf.file.public_id, format: :jpg, density: 300, width: 800, :id => "trim", :class => "original-preview" %>
  </div>
  <div class="selected-card">
    <%= @section.final_content %>
  </div>
  <div>

  </div>
</div> -->

<div class="show-container">
  <div class="show-tabs">
    <ul class="login-nav nav nav-justified">
      <li role="presentation" class="active"><a href="#show-original" data-toggle="tab">ORIGINAL PDF</a></li>
      <li role="presentation"><a href="#your-section" data-toggle="tab"><%= @section.student.first_name.upcase %>' SECTION</a></li>
      <li role="presentation"><a href="#show-final" data-toggle="tab">FINAL PDF</a></li>
    </ul>
  </div>

  <div class="content-box">
    <div class="tab-content">
      <div class="tab-pane active" id="show-original">
        <%= cl_image_tag @document.pdf.file.public_id, format: :jpg, density: 300, width: 800, :id => "trim", :class => "document" %>
      </div>
      <div class="tab-pane" id="your-section">
        <div class="selected-card">
          <%= @section.final_content %>
        </div>
      </div>
      <div class="tab-pane" id="show-final">
        <%= cl_image_tag @document.final_pdf.file.public_id, format: :jpg, density: 300, width: 800, :id => "trim", :class => "document" %>
      </div>
    </div>

  </div>
</div>