config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :documents do
    resources :sections do
      member do
        patch "teacher_update", to: "sections#teacher_update"
      end
    end
  end
  resources :lessons
  resources :student_lessons
  resources :users
    resources :orders, only: [:show, :create] do
    resources :payments, only: [:new, :create]
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :set_order
  # after_action :update_document_status, only: [ :create ]

  def new
  end

  def create
    customer = Stripe::Customer.create(
    source: params[:stripeToken],
    email:  params[:stripeEmail]
  )

  charge = Stripe::Charge.create(
    customer:     customer.id,   # You should store this customer id and re-use it.
    amount:       @order.amount_cents,
    description:  "Payment for document (title) for order #{@order.id}",
    currency:     @order.amount.currency
  )

  if @order.update(payment: charge.to_json, state: 'paid')
    doc = @order.document
    doc.student_content = "paid"
    doc.save!
  end

  redirect_to user_path(current_user)

  rescue Stripe::CardError => e
    flash[:alert] = e.message
    redirect_to new_order_payment_path(@order)
  end

private

  def set_order
    @order = current_user.orders.where(state: 'pending').find(params[:order_id])
  end
end

app/views/payments/_paymentform.html.erb
<div class="payment">
<p>Translation of <%= document.title %></p>
<%= form_tag order_payments_path(order) do %>
<div class="align">
  <article>
    <label class="amount">
      <span>Price: <%= humanized_money_with_symbol(order.amount) %></span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
    data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
    data-name="New Upload"
    data-email="<%= current_user.email %>"
    data-description="<%=document.title  %>"
    data-amount="<%= order.amount_cents %>"
    data-currency="<%= order.amount.currency %>"></script>
</div>

<% end %>
</div>

app/views/payments/new.html.erb
<%= render 'paymentform', order: @order, document: @document %>